### ISSUE TITLE
Warning during build

### ISSUE THREAD

**Issue by rborosak** [Megaputer/dts-css-modules-loader#1]
I'm using this loader with pure css files and it works great. 
css.d.ts files get generated when I use style in component but when I run build I get a warning

WARNING in ./src/components/core/ribbon/ribbon.css.d.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for C:\git_personal\src\components\core\ribbon\ribbon.css.d.ts.
    at makeSourceMapAndFinish (C:\git_personal\node_modules\ts-loader\dist\index.js:78:15)
    at successLoader (C:\git_personal\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\git_personal\node_modules\ts-loader\dist\index.js:22:12)
 @ ./src/components sync ^\.\/.*$ ./core/ribbon/ribbon.css.d
 @ ./src/components/routes/AppRoutes.tsx
 @ ./src/components/core/ContentContainer.tsx
 @ ./src/components/Home.tsx
 @ ./src/components/routes/MainRoutes.tsx
 @ ./src/components/entryPoints/EntryPoint.tsx
 @ ./src/components/entryPoints sync ^\.\/.*$
 @ ./src/App.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/App.tsx

And my component looks like this

import * as globalStyles from '../../../../assets/styles/globals.css'
import * as styles from './ribbon.css'

export const Ribbon: FunctionComponent = (props) => {
    return (
        <nav className={globalStyles.blueBackground}>
            <ul className={`${styles.nav} ${globalStyles.globalNav}`}>
            .........
            </ul>
        </nav>
)

and ribbon.css.d.ts
// This file is generated automatically
export const nav: string;

It's interesting that I don't get any warnings from globals.css.d.ts but only for ribbon.css.d.ts

What could be the cause of this warning and how can it be fixed?

**Comment by c0gnize** [comment]
It seems that webpack tries to build your d.ts files. May be be related with this https://stackoverflow.com/questions/38231645/typescriptwebpack-typescript-emmited-no-output-for-index-d-ts

**Comment by rborosak** [comment]
Thank you.. Following your link I've got it to work.
I've added ignore loader just before ts loader and told ts loader to ignore .css.d files
Here is a part of my webpack.config if anyone would need it

```
{
                test: /(?<!\.css\.d)\.(ts|tsx)$/,
                use: [{
                    loader: "ts-loader",
                    options: {
                        transpileOnly: true,
                        experimentalWatchApi: true,
                    }
                }]
            },
            {
                test: /\.css\.d\.ts$/,
                loader: 'ignore-loader'
            },
```
