### ISSUE TITLE
Option namedExport can conflict with exportOnlyLocals from css-loader

### ISSUE THREAD

**Issue by c0gnize** [Megaputer/dts-css-modules-loader#11]
Option namedExport can conflict with [exportOnlyLocals ](https://github.com/webpack-contrib/css-loader#exportonlylocals) so the generated typings will not reflect the output of [css-loader](https://github.com/webpack-contrib/css-loader).

Also, need to rename `styles` to `locals` at:
https://github.com/Megaputer/dts-css-modules-loader/blob/920e3742b12c2a068fa42345d96d1d7f39cd9a63/index.js#L32

**Comment by maapteh** [comment]
Cool module! Any idea when you will fix?
`Object literal may only specify known properties, and 'namedExport' does not exist in type`

**Comment by c0gnize** [comment]
Closed by 2d587d824b9ade688b6f2e06dd41f1c0f0ab26da

**Comment by c0gnize** [comment]
I was wrong with this issue, due to invalid `webpack.config.js`.  Sorry for misleading you. Reverted the upper commit with 690480c3cd2e006f473aab95020bd7728c16db43
