### ISSUE TITLE
[question] Module should maybe skip @keyframe names?

### ISSUE THREAD

**Issue by maapteh** [Megaputer/dts-css-modules-loader#12]
We have for example:
```

@keyframes correct-icon {
    0% {
        opacity: 0;
    }

    15% {
        opacity: 1;
    }

    80% {
        opacity: 1;
    }

    100% {
        opacity: 0;
    }
}
```

But keyframes can never be consumed in the component. What is the best approach? Besides renaming them :)

**Comment by c0gnize** [comment]
You are right. I will change the loader to skip keyframe names.

**Comment by maapteh** [comment]
Any idea when?

**Comment by c0gnize** [comment]
Sorry for a long delay. I was around a week without access to the internet. After research, I found that `dts-css-modules-loader` may not have enough information that some name is a keyframe. So there is no way to drop them in the current loader.

**Comment by maapteh** [comment]
no worries thanks for the update! i will try to see if i can make it work. For now i also changed the mixins patterns :)

**Comment by c0gnize** [comment]
I think we can close this issue
