### ISSUE TITLE
Peer dependency warning with latest css-loader

### ISSUE THREAD

**Issue by jens-duttke** [Megaputer/dts-css-modules-loader#13]
npm throws a warning, if `dts-css-modules-loader` is used with the latest version of `css-loader` (3.4.2 right now):

> npm WARN dts-css-modules-loader@1.0.1 requires a peer of css-loader@^2.0.2 but none is installed. You must install peer dependencies yourself.

I don't know why you rely on this old version, because your package works fine with the latest `css-loader`.

Can you please adjust your `package.json` to get rid of the warning?
Maybe changing it to ">=2.0.2" would be a solution (if you know that 2.0.2 is the minimum requirement). In that case, your extension would work with all further `css-loader` versions. If there should be a breaking-change in `css-loader` someday, I'm sure someone creates a ticket in your issue tracker.

**Comment by c0gnize** [comment]
Ok. I will check loader with the new 3 version of `css-loader` and replace the dependency with:
`"css-loader": "^2.0.0 || ^3.0.0"`. Thank you!
