### ISSUE TITLE
Outdated css-loader peer dependency

### ISSUE THREAD

**Issue by jens-duttke** [Megaputer/dts-css-modules-loader#20]
Using the new `css-loader` version `5.0.0`, I'm getting the npm warning:
```
npm WARN dts-css-modules-loader@1.1.0 requires a peer of css-loader@^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
```
`dts-css-modules-loader` works without any problems with css-loader 5, so there is no need for this restriction.

**Comment by c0gnize** [comment]
I haven't tested for compatibility with the `css-loader` version `5.0.0` yet. I will update the peer dependencies soon.
