### ISSUE TITLE
Generates invalid dts file when using @import in PostCSS files

### ISSUE THREAD

**Issue by Manc** [Megaputer/dts-css-modules-loader#5]
I'm trying to use PostCSS (`postcss-loader`) with `css-loader` and `dts-css-modules-loader`.

Whenever I have a line like `@import '../variables.pcss';` in one of my PostCSS files, the resulting `.d.ts` file starts like this:

```
// This file is generated automatically
export const ));

// Module
exports.push([module.id, : string;
export const testclass: string;
```

The rest of the classes follow as expected, but obviously the first few lines are not right. It worked with the old `typings-for-css-modules-loader`. Do you have any ideas why this could be?

My PostCSS config is set up in a way that the actual imports should be replaced with the inlined content of the imported file (module [postcss-import](https://github.com/postcss/postcss-import)), so to my understanding there shouldn't be any `@import`s anymore anyway when the `postcss-loader` is done. I also use the [postcss-css-variables](https://github.com/MadLittleMods/postcss-css-variables) plugin, which should replace all variables with actual values. The resulting CSS is indeed very plain simple CSS, with no imports and no variables.

Before I post lots of code or something, just wanted to ask if you have any ideas already... Thanks!

**Comment by Manc** [comment]
I think it has to do with the RegEx... I'll let you know when I have a solution...

**Comment by c0gnize** [comment]
I waited for RegEx for the class name will give slack, but I had no idea how this could happen. Thank you @Manc for the pull request.
