### ISSUE TITLE
react+ts+less+ExtractTextPlugin build error!!

### ISSUE THREAD

**Issue by udbbbn** [Megaputer/dts-css-modules-loader#8]
error msg: 

`    ERROR in ./src/components/hello.less (./node_modules/dts-css-modules-loader??ref--5-1!./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/less-loader/dist/cjs.js!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/dts-css-modules-loader??ref--6-2!./node_modules/css-loader/dist/cjs.js??ref--6-3!./node_modules/less-loader/dist/cjs.js??ref--6-4!./src/components/hello.less)
    Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    
    var content = require("!!../../node_modules/dts-css-modules-loader/index.js??ref--6-2!../../node_modules/css-loader/dist/cjs.js??ref--6-3!../../node_modules/less-loader/dist/cjs.js??ref--6-4!./hello.less");
    ^
    Unrecognised input
    in C:\Users\Administrator\Desktop\zzm\Blog\src\components\hello.less (line 2, column 12)
    @ ./src/components/hello.less 2:14-474
    @ ./src/components/hello.tsx
    @ ./src/index.tsx
    
    ERROR in ./src/components/hello.less (./node_modules/dts-css-modules-loader??ref--5-1!./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/less-loader/dist/cjs.js!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/dts-css-modules-loader??ref--6-2!./node_modules/css-loader/dist/cjs.js??ref--6-3!./node_modules/less-loader/dist/cjs.js??ref--6-4!./src/components/hello.less)
    Module build failed (from ./node_modules/less-loader/dist/cjs.js):
    
    // removed by extract-text-webpack-plugin
    module.exports = {"hello":"v_MARsXVms7uJk7ONLnLi"};
    ^
    Unrecognised input
    in C:\Users\Administrator\Desktop\zzm\Blog\src\components\hello.less (line 2, column 15)
    @ ./src/components/hello.less (./node_modules/dts-css-modules-loader??ref--5-1!./node_modules/css-loader/dist/cjs.js??ref--5-2!./node_modules/less-loader/dist/cjs.js!./node_modules/extract-text-webpack-plugin/dist/loader.js??ref--6-0!./node_modules/style-loader!./node_modules/dts-css-modules-loader??ref--6-2!./node_modules/css-loader/dist/cjs.js??ref--6-3!./node_modules/less-loader/dist/cjs.js??ref--6-4!./src/components/hello.less)`

**If I don't use ExtractTextPlugin, then no problem!!**

this is my webpack config :

**webpack.common.config.js**

`	
	const path = require('path');
	const webpack = require('webpack');
	const HtmlWebpackPlugin = require('html-webpack-plugin');

	module.exports = {
    entry: {
        app: "./src/index.tsx"
    },
    output: {
        path: path.resolve(__dirname, "dist"),
        publicPath: "/",
        filename: "bundle.js"
    },
    resolve: {
        extensions: [".ts", ".tsx", ".js"],
        alias: {
            "@": path.resolve(__dirname, "src")
        }
    },
    module: {
        rules: [
            {
                test: /\.ts(x?)$/,
                loader: "ts-loader"
            },
            // {
            //     test: /\.css$/,
            //     // loader: "css-loader"  
            //     loader: "css-loader"  
            // },
            {
                test: /\.less$/,
                include: [
                    path.resolve(__dirname, 'src')
                ],
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                      loader: 'dts-css-modules-loader',
                      options: {
                        namedExport: true,
                      }
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            // 是否用css module
                            modules: true,
                            // 支持驼峰
                            camelCase: true
                        }
                    },
                    {
                        loader: 'less-loader'
                    }
                ]
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: __dirname + '/public/index.html'
        }),
        // 无视.d.ts
        new webpack.WatchIgnorePlugin([
          /less\.d\.ts$/
        ]),
    ]
}`

**webpack.pro.config**

`    const path = require('path');
	const webpack = require('webpack');
	const config = require('./webpack.common.config');
	const merge = require('webpack-merge');
	const ExtractTextPlugin = require('extract-text-webpack-plugin'); // 分离css
	const CleanWebpackPlugin = require('clean-webpack-plugin'); // 清空文件夹
	const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin; // bundle可视化工具
	const HtmlWebpackPlugin = require('html-webpack-plugin');

	module.exports = merge(config, {
    externals: {
        "react": "React",
        "react-dom": "ReactDOM",
        "redux": "Redux"
    },
    output: {
        filename: "bundle.[chunkhash].js"
    },
    mode: "production",
    module: {
        rules: [
            {
                test: /(\.less)$/,
                exclude: /node_modules/,
                include: [
                    path.resolve(__dirname, 'src')
                ],
                use: ExtractTextPlugin.extract({
                    fallback: [
                        {
                            loader: "style-loader",
                        },
                    ],
                    use: [
                        {
                            loader: 'dts-css-modules-loader',
                            options: {
                                namedExport: true,
                            }
                        },
                        {
                            loader: 'css-loader',
                            options: {
                                // 是否用css module
                                modules: true,
                                // 支持驼峰
                                camelCase: true
                            }
                        },
                        {
                            loader: 'less-loader',
                            options: {
                                javascriptEnabled: true
                            }
                        }
                    ]
                })
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin({
                root: path.resolve(__dirname, 'dist'),
                exclude: ['assets'],
                dry: false // 启用删除文件
        }),
        new ExtractTextPlugin({ 
            filename: '[name].[hash:8].css' // 配置提取出来的css名称
        }),
        new HtmlWebpackPlugin({
            inject: 'body',
            template: __dirname + '/public/index.html',
            filename: "index.html",
            minify: {
              removeComments: true,
              collapseWhitespace: true,
              removeRedundantAttributes: true,
              useShortDoctype: true,
              removeEmptyAttributes: true,
              removeStyleLinkTypeAttributes: true,
              keepClosingSlash: true,
              minifyJS: true,
              minifyCSS: true,
              minifyURLs: true,
            },
        }),
        // bundle 可视化工具
        new BundleAnalyzerPlugin({
            analyzerMode: 'server',
            analyzerHost: '127.0.0.1',
            analyzerPort: 8889,
            reportFilename: 'report.html',
            defaultSizes: 'parsed',
            openAnalyzer: true,
            generateStatsFile: false,
            statsFilename: 'stats.json',
            statsOptions: null,
            logLevel: 'info'
        }),
    ],
    // 提取公共模块
    optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "vendor",
                    chunks: "all"
                }
            }
        },
    }
})
`

**Comment by c0gnize** [comment]
@udbbbn, I recommend you to use [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin), instead off [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin)

**Comment by udbbbn** [comment]
ok thanks
