### ISSUE TITLE
Export named namespace

### ISSUE THREAD

**Issue by aleksfes** [Megaputer/dts-css-modules-loader#9]
Currently, default exports are deprecated in my project.

I think that css.d.ts file should export a namespace variable as an alternative way.

**Comment by c0gnize** [comment]
Sorry, but currently this is impossible.

More precisely, we can add this ability to `dts-css-modules-loader` but [css-loader](https://github.com/webpack-contrib/css-loader) will generate code in the old way. So `typescript` will successfully compile the code, but browser will throw an error while trying to attempt this variable.

[css-loader](https://github.com/webpack-contrib/css-loader) can generate two variants of js code:

`exportonlylocals: true`:
```
module.exports = {
  "button": "button",
  "buttonActive": "button--active",
...
```

`exportonlylocals: false`:
```
exports = module.exports = require("../../node_modules/css-loader/dist/runtime/api.js")(false);
// Module
exports.push([module.id, "...", ""]);
// Exports
exports.locals = {
  "button": "button",
  "buttonActive": "button--active",
...
```

And there is no ability to customize the name. By the way, I just realized that `dts-css-modules-loader` will not work correctly with `exportonlylocals: false`

As an alternative, I can offer you to use `exportonlylocals: true` and import class name as:
```
import { paButton } from './_button.scss';
```

**Comment by aleksfes** [comment]
Hi, @c0gnize , thanks a lot for the answer! I've got it, you are right - I didn't check my app completely, build only. Maybe, I will try to make a PR to css-loader, but not now, unfortunatelly.
